# Generated by Django 5.2 on 2025-06-26 03:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('task_type', models.CharField(choices=[('classification', 'Classification'), ('regression', 'Regression')], max_length=20)),
                ('dataset_name', models.CharField(max_length=200)),
                ('target_column', models.CharField(max_length=100)),
                ('features_list', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('training', 'Training'), ('completed', 'Completed'), ('failed', 'Failed')], default='training', max_length=20)),
                ('progress', models.IntegerField(default=0)),
                ('model_path', models.CharField(blank=True, max_length=500)),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'name')},
            },
        ),
    ]
