# Generated by Django 5.2 on 2025-06-26 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MLPlatformApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodel',
            name='downloads_count',
            field=models.IntegerField(default=0),
        ),
    ]
