# Generated by Django 5.2 on 2025-06-26 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MLPlatformApp', '0002_aimodel_downloads_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aimodel',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='aimodel',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='aimodel',
            name='downloads_count',
        ),
    ]
