# Generated by Django 5.2 on 2025-06-26 18:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MLPlatformApp', '0003_alter_aimodel_options_alter_aimodel_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('input_data', models.JSONField()),
                ('prediction_result', models.JSONField()),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('is_public_model', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ai_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MLPlatformApp.aimodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['ai_model', 'user', 'created_at'], name='MLPlatformA_ai_mode_08a1b8_idx'), models.Index(fields=['user', 'created_at'], name='MLPlatformA_user_id_fc8607_idx')],
            },
        ),
    ]
