# Generated by Django 5.2 on 2025-06-27 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MLPlatformApp', '0004_predictionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodel',
            name='model_metrics',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
