# Generated by Django 5.2 on 2025-07-18 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MLPlatformApp', '0005_aimodel_model_metrics'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodel',
            name='training_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aimodel',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('training', 'Training'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
