# Generated by Django 5.2 on 2025-05-26 04:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CSVModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='csv_uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('target_column', models.CharField(blank=True, max_length=255, null=True)),
                ('processed_file', models.FileField(blank=True, null=True, upload_to='csv_processed/')),
                ('report_image_outliers', models.TextField(blank=True, null=True)),
                ('report_image_distribution', models.TextField(blank=True, null=True)),
                ('report_image_missing', models.TextField(blank=True, null=True)),
                ('is_ready', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='csvs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
