# Generated by Django 5.2 on 2025-05-29 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PreprocessingApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='csvmodel',
            name='is_ready',
        ),
        migrations.AddField(
            model_name='csvmodel',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('completed', 'Completado'), ('failed', 'Fallido')], default='pending', max_length=10),
        ),
    ]
