# Generated by Django 5.2 on 2025-05-30 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PreprocessingApp', '0003_csvmodel_is_ready'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='csvmodel',
            name='status',
        ),
        migrations.RemoveField(
            model_name='csvmodel',
            name='target_column',
        ),
    ]
