# Generated by Django 5.2 on 2025-06-04 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PreprocessingApp', '0004_remove_csvmodel_status_remove_csvmodel_target_column'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvmodel',
            name='processed_file',
            field=models.FileField(blank=True, null=True, upload_to='csv_uploads/'),
        ),
    ]
