# Generated by Django 5.2 on 2025-06-04 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PreprocessingApp', '0005_alter_csvmodel_processed_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='csvmodel',
            name='report_image_distribution',
        ),
        migrations.RemoveField(
            model_name='csvmodel',
            name='report_image_missing',
        ),
        migrations.RemoveField(
            model_name='csvmodel',
            name='report_image_outliers',
        ),
    ]
