# Generated by Django 5.2 on 2025-06-04 21:38

import PreprocessingApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PreprocessingApp', '0006_remove_csvmodel_report_image_distribution_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvmodel',
            name='file',
            field=models.FileField(upload_to=PreprocessingApp.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='csvmodel',
            name='processed_file',
            field=models.FileField(blank=True, null=True, upload_to=PreprocessingApp.models.user_directory_path),
        ),
    ]
