# Generated by Django 5.2 on 2025-06-17 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PreprocessingApp', '0007_alter_csvmodel_file_alter_csvmodel_processed_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvmodel',
            name='processing_type',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='csvmodel',
            name='target_column',
            field=models.TextField(blank=True, null=True),
        ),
    ]
