# Generated by Django 5.2.3 on 2025-06-20 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PreprocessingApp', '0008_csvmodel_processing_type_csvmodel_target_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvmodel',
            name='drop_column',
            field=models.TextField(blank=True, null=True),
        ),
    ]
