# Generated by Django 5.2.3 on 2025-06-20 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PreprocessingApp', '0009_csvmodel_drop_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvmodel',
            name='original_filename',
            field=models.CharField(default='', max_length=255),
        ),
    ]
